# Generated by Django 5.2.4 on 2025-07-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("campaign_manager", "Campaign Manager"),
                    ("registration_clerk", "Registration Clerk"),
                    ("vitals_clerk", "Vitals Clerk"),
                    ("doctor", "Doctor"),
                    ("lab_technician", "Lab Technician"),
                    ("pharmacy_clerk", "Pharmacy Clerk"),
                    ("data_analyst", "Data Analyst"),
                ],
                default="registration_clerk",
                help_text="User role determines permissions and access level",
                max_length=50,
            ),
        ),
    ]
