# Generated by Django 5.2.4 on 2025-07-16 06:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("campaign_manager", "Campaign Manager"),
                    ("registration_clerk", "Registration Clerk"),
                    ("vitals_clerk", "Vitals Clerk"),
                    ("doctor", "Doctor"),
                    ("lab_technician", "Lab Technician"),
                    ("pharmacy_clerk", "Pharmacy Clerk"),
                    ("data_analyst", "Data Analyst"),
                ],
                default="registration_clerk",
                help_text="User's role in the health campaign",
                max_length=50,
            ),
        ),
    ]
