# Generated by Django 5.2.4 on 2025-07-31 17:20

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings


def create_superuser(apps, schema_editor):
    """
    Create a default superuser account for production deployment
    """
    User = get_user_model()

    # Check if superuser already exists
    if not User.objects.filter(is_superuser=True).exists():
        # Create superuser with default credentials
        superuser = User.objects.create_user(
            username='admin',
            email='admin@tikohealthcampaign.com',
            password='TikoAdmin2025!',  # Change this after first login
            first_name='System',
            last_name='Administrator',
            role='admin',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        print(f"Superuser created: {superuser.username}")
    else:
        print("Superuser already exists, skipping creation")


def reverse_create_superuser(apps, schema_editor):
    """
    Remove the default superuser (for migration rollback)
    """
    User = get_user_model()
    try:
        superuser = User.objects.get(username='admin', email='admin@tikohealthcampaign.com')
        superuser.delete()
        print("Default superuser removed")
    except User.DoesNotExist:
        print("Default superuser not found, nothing to remove")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_create_superuser),
    ]
