# Generated by Django 5.2.4 on 2025-07-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20250731_2227"),
    ]

    operations = []
