# Generated by Django 5.2.4 on 2025-07-31 21:35

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model


def assign_admin_to_administrators_group(apps, schema_editor):
    """
    Assign the admin user to the Administrators group
    """
    User = get_user_model()

    try:
        # Get the admin user
        admin_user = User.objects.get(username='admin')

        # Get the Administrators group
        admin_group = Group.objects.get(name='Administrators')

        # Add user to group
        admin_user.groups.add(admin_group)
        admin_user.save()

        print(f"Added {admin_user.username} to {admin_group.name} group")

    except User.DoesNotExist:
        print("Admin user not found")
    except Group.DoesNotExist:
        print("Administrators group not found")


def reverse_assign_admin_to_administrators_group(apps, schema_editor):
    """
    Remove admin user from Administrators group
    """
    User = get_user_model()

    try:
        admin_user = User.objects.get(username='admin')
        admin_group = Group.objects.get(name='Administrators')
        admin_user.groups.remove(admin_group)
        admin_user.save()
        print(f"Removed {admin_user.username} from {admin_group.name} group")
    except (User.DoesNotExist, Group.DoesNotExist):
        print("Admin user or Administrators group not found")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20250731_2233"),
    ]

    operations = [
        migrations.RunPython(assign_admin_to_administrators_group, reverse_assign_admin_to_administrators_group),
    ]
