# Generated by Django 5.2.4 on 2025-07-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20250731_2233"),
    ]

    operations = []
