# Generated by Django 5.2.4 on 2025-07-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_assign_admin_to_group"),
    ]

    operations = []
