# Generated by Django 5.2.4 on 2025-08-01 10:19

from django.db import migrations
from django.contrib.auth import get_user_model


def create_admin_user(apps, schema_editor):
    """
    Create a simple admin user for production access
    """
    User = get_user_model()

    # Check if any admin user exists
    if not User.objects.filter(is_superuser=True).exists():
        # Create admin user
        admin_user = User.objects.create_user(
            username='admin',
            email='admin@tikohealthcampaign.com',
            password='TikoAdmin2025!',
            first_name='System',
            last_name='Administrator',
            role='admin',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        print(f"Created admin user: {admin_user.username}")
    else:
        print("Admin user already exists")


def reverse_create_admin_user(apps, schema_editor):
    """
    Remove the admin user
    """
    User = get_user_model()
    try:
        admin_user = User.objects.get(username='admin')
        admin_user.delete()
        print("Removed admin user")
    except User.DoesNotExist:
        print("Admin user not found")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_create_admin_user"),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
