# Generated by Django 5.2.4 on 2025-08-01 10:27

from django.db import migrations
from django.contrib.auth.models import Group


def setup_basic_groups(apps, schema_editor):
    """
    Create basic user groups
    """
    group_names = [
        'Registration Clerks',
        'Vitals Clerks',
        'Doctors',
        'Lab Technicians',
        'Pharmacy Clerks',
        'Campaign Managers',
        'Data Analysts',
        'Administrators',
    ]

    for group_name in group_names:
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f"Created group: {group_name}")


def reverse_setup_basic_groups(apps, schema_editor):
    """
    Remove basic groups
    """
    group_names = [
        'Registration Clerks',
        'Vitals Clerks',
        'Doctors',
        'Lab Technicians',
        'Pharmacy Clerks',
        'Campaign Managers',
        'Data Analysts',
        'Administrators',
    ]

    for group_name in group_names:
        try:
            group = Group.objects.get(name=group_name)
            group.delete()
            print(f"Removed group: {group_name}")
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_create_admin_user"),
    ]

    operations = [
        migrations.RunPython(setup_basic_groups, reverse_setup_basic_groups),
    ]
