# Generated by Django 5.2.4 on 2025-07-15 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        help_text="Patient's main complaint or reason for visit"
                    ),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        blank=True,
                        help_text="Detailed history of the current illness",
                        null=True,
                    ),
                ),
                (
                    "past_medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Previous medical conditions, surgeries, hospitalizations",
                        null=True,
                    ),
                ),
                (
                    "family_history",
                    models.TextField(
                        blank=True,
                        help_text="Relevant family medical history",
                        null=True,
                    ),
                ),
                (
                    "social_history",
                    models.TextField(
                        blank=True,
                        help_text="Lifestyle factors, occupation, habits",
                        null=True,
                    ),
                ),
                (
                    "general_appearance",
                    models.TextField(
                        blank=True,
                        help_text="General appearance and mental state",
                        null=True,
                    ),
                ),
                (
                    "physical_examination",
                    models.TextField(
                        blank=True,
                        help_text="Detailed physical examination findings",
                        null=True,
                    ),
                ),
                (
                    "clinical_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Clinical impression and assessment",
                        null=True,
                    ),
                ),
                (
                    "working_diagnosis",
                    models.TextField(help_text="Primary and differential diagnoses"),
                ),
                (
                    "treatment_plan",
                    models.TextField(
                        blank=True,
                        help_text="Treatment plan and recommendations",
                        null=True,
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Follow-up instructions for patient",
                        null=True,
                    ),
                ),
                ("referral_needed", models.BooleanField(default=False)),
                (
                    "referral_to",
                    models.CharField(
                        blank=True,
                        help_text="Specialist or facility for referral",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "referral_reason",
                    models.TextField(
                        blank=True, help_text="Reason for referral", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("follow_up_needed", "Follow-up Needed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or observations",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-consultation_date"],
                "permissions": [
                    ("can_conduct_consultations", "Can conduct medical consultations"),
                    ("can_view_consultation_reports", "Can view consultation reports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="e.g., 500mg, 1 tablet, 5ml", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., twice daily, every 8 hours, as needed",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., 7 days, 2 weeks, until finished",
                        max_length=100,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("topical", "Topical"),
                            ("injection", "Injection"),
                            ("inhalation", "Inhalation"),
                            ("other", "Other"),
                        ],
                        default="oral",
                        max_length=50,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for taking the medication",
                        null=True,
                    ),
                ),
                (
                    "indication",
                    models.CharField(
                        blank=True,
                        help_text="What the medication is for",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total quantity to dispense", null=True
                    ),
                ),
                (
                    "refills",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of refills allowed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prescribed", "Prescribed"),
                            ("dispensed", "Dispensed"),
                            ("partially_dispensed", "Partially Dispensed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="prescribed",
                        max_length=20,
                    ),
                ),
                ("dispensed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dispensed_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Actual quantity dispensed", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="campaigns.drug"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "clinical_indication",
                    models.TextField(
                        blank=True,
                        help_text="Clinical reason for ordering this test",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("collected", "Sample Collected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_date"],
                "unique_together": {("consultation", "lab_test")},
            },
        ),
    ]
