# Generated by Django 5.2.4 on 2025-07-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="laborder",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="laborder",
            name="custom_test_name",
            field=models.CharField(
                blank=True,
                help_text="Custom lab test name (if not in formulary)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="laborder",
            name="lab_test",
            field=models.ForeignKey(
                blank=True,
                help_text="Select from campaign formulary (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.labtest",
            ),
        ),
    ]
