# Generated by Django 5.2.4 on 2025-07-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("consultations", "0002_alter_laborder_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="custom_drug_name",
            field=models.CharField(
                blank=True,
                help_text="Custom drug name (if not in formulary)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="drug",
            field=models.ForeignKey(
                blank=True,
                help_text="Select from campaign formulary (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.drug",
            ),
        ),
    ]
