# Generated by Django 5.2.4 on 2025-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_prescription_custom_drug_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="pharmacy_status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Pharmacy Review"),
                    ("details_needed", "Dosage Details Needed"),
                    ("ready_to_dispense", "Ready to Dispense"),
                    ("dispensed", "Dispensed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_review",
                help_text="Pharmacy workflow status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="dosage",
            field=models.CharField(
                blank=True,
                help_text="e.g., 500mg, 1 tablet, 5ml (can be completed by pharmacy)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="e.g., 7 days, 2 weeks, until finished (can be completed by pharmacy)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="frequency",
            field=models.CharField(
                blank=True,
                help_text="e.g., twice daily, every 8 hours, as needed (can be completed by pharmacy)",
                max_length=100,
                null=True,
            ),
        ),
    ]
