# Generated by Django 5.2.4 on 2025-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0004_prescription_pharmacy_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="lab_status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("sample_collected", "Sample Collected"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="ordered",
                help_text="Laboratory workflow status",
                max_length=20,
            ),
        ),
    ]
