# Generated by Django 5.2.4 on 2025-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0005_laborder_lab_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="chief_complaint",
            field=models.TextField(
                blank=True,
                help_text="Patient's main complaint or reason for visit",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="working_diagnosis",
            field=models.TextField(
                blank=True, help_text="Primary and differential diagnoses", null=True
            ),
        ),
    ]
