# Generated by Django 5.2.4 on 2025-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0006_alter_consultation_chief_complaint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborder",
            name="lab_status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="ordered",
                help_text="Laboratory status: Ordered or Completed",
                max_length=20,
            ),
        ),
    ]
