# Generated by Django 5.2.4 on 2025-07-15 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "normal_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("blood", "Blood Test"),
                            ("urine", "Urine Test"),
                            ("stool", "Stool Test"),
                            ("imaging", "Imaging"),
                            ("other", "Other"),
                        ],
                        default="blood",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("health_area", models.CharField(max_length=200)),
                (
                    "consent_text",
                    models.TextField(
                        help_text="Consent text that patients will agree to during registration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_patients",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of patients for this campaign (optional)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_manage_campaigns", "Can manage campaigns"),
                    ("can_view_campaign_reports", "Can view campaign reports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "generic_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("strength", models.CharField(blank=True, max_length=50, null=True)),
                ("dosage_form", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("analgesic", "Analgesic"),
                            ("antibiotic", "Antibiotic"),
                            ("antihypertensive", "Antihypertensive"),
                            ("antidiabetic", "Antidiabetic"),
                            ("vitamin", "Vitamin/Supplement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("name", "strength", "dosage_form")},
            },
        ),
        migrations.CreateModel(
            name="CampaignDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this drug will be highlighted as preferred",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Available stock for this campaign (optional)",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulary",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="campaigns.drug"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "drug__name"],
                "unique_together": {("campaign", "drug")},
            },
        ),
        migrations.CreateModel(
            name="CampaignLabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this test will be automatically selected for new patients",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "lab_test__name"],
                "unique_together": {("campaign", "lab_test")},
            },
        ),
    ]
